import './globals.css'
import { Inter, Roboto, Roboto_Mono } from 'next/font/google'

const roboto = Roboto_Mono({ subsets: ['latin'], weight: "500" })

export const metadata = {
    title: 'SEVEN B SRL',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={roboto.className}>{children}</body>
        </html>
    )
}
